# To be tested and completed
version: '3'
services:
    db:
        image: postgres
        volumes:
        - ./sql_service/db:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
            - "5433:5432"
    auth_service:
        build: ./auth_service
        volumes:
            - ./auth_service:/code
        ports: 
            - 8000:8000
        
            
    