# Generated by Django 4.0.3 on 2022-04-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image1_alter_user_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='London', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=255),
            preserve_default=False,
        ),
    ]
